import {
  type GraphQLObjectType,
  type GraphQLSchema,
  isInterfaceType,
  isNonNullType,
  isObjectType,
} from 'graphql';
import type { ResolvedTypePoliciesPluginConfig } from '../config';
import type { TypeTransformation } from '../parser';

interface GeneratorOptions {
  preserveNullability: boolean;
  debug: boolean;
}

/**
 * Generate TypeScript type overrides based on extracted transformations
 */
export function generateTypeOverrides(
  schema: GraphQLSchema,
  transformations: Map<string, TypeTransformation>,
  config: ResolvedTypePoliciesPluginConfig
): string {
  const lines: string[] = [];
  const options: GeneratorOptions = {
    preserveNullability: config.preserveNullability,
    debug: config.debug,
  };

  lines.push('/* eslint-disable */');
  lines.push('/* This file was generated by graphql-codegen-apollo-typepolicies */');
  lines.push('/* Do not edit this file directly */');
  lines.push('');

  if (transformations.size === 0) {
    lines.push('// No type policy transformations found');
    return lines.join('\n');
  }

  // Mirror Apollo's runtime behavior: a read on an interface fans out to every
  // implementing object type. Expansion happens before filtering so the rest of
  // the pipeline only ever sees concrete object-type entries.
  const expandedTransformations = expandInterfaceTransformations(
    transformations,
    schema,
    config.debug
  );

  // Drop transformations whose GraphQL type is missing or not an object type.
  // After expansion, interface entries are gone — this only catches unions,
  // scalars, enums, and missing types.
  const filteredTransformations = new Map<string, TypeTransformation>();
  for (const [key, transform] of expandedTransformations) {
    const graphqlType = schema.getType(transform.typeName);
    if (!graphqlType) {
      if (config.debug) {
        console.warn(`[debug] Type "${transform.typeName}" not found in GraphQL schema, skipping`);
      }
      continue;
    }
    if (!isObjectType(graphqlType)) {
      if (config.debug) {
        console.warn(`[debug] Type "${transform.typeName}" is not an object type, skipping`);
      }
      continue;
    }
    filteredTransformations.set(key, transform);
  }

  if (filteredTransformations.size === 0) {
    lines.push('// No type policy transformations found');
    return lines.join('\n');
  }

  // Generate TypePolicyTransformations interface
  lines.push('/**');
  lines.push(' * Map of all type policy field transformations.');
  lines.push(' * Key format: "TypeName.fieldName"');
  lines.push(' */');
  lines.push('export interface TypePolicyTransformations {');

  for (const [key, transform] of filteredTransformations) {
    lines.push(`  '${key}': ${transform.transformedType};`);
  }

  lines.push('}');
  lines.push('');

  // Group transformations by type name
  const typeGroups = groupTransformationsByType(filteredTransformations);

  // Generate transformed type for each GraphQL type that has transformations.
  // Filtering above guarantees every typeName resolves to an object type.
  for (const [typeName, fieldTransforms] of typeGroups) {
    const graphqlType = schema.getType(typeName) as GraphQLObjectType;
    lines.push(generateTransformedType(graphqlType, fieldTransforms, options));
  }

  // Generate utility type for applying transformations to query results
  lines.push(generateUtilityTypes(typeGroups));

  return lines.join('\n');
}

/**
 * Expand interface-targeted transformations into per-implementing-type
 * transformations. Apollo Client applies a `read` on an interface to every
 * concrete type that implements the interface — we mirror that in the type
 * system so WithTypePolicies reflects the runtime shape.
 *
 * Concrete-type transformations always win over interface fan-outs for the
 * same (typeName, fieldName) pair.
 *
 * Non-object, non-interface entries (unions, scalars, enums, missing) pass
 * through untouched; the downstream filter handles them.
 */
function expandInterfaceTransformations(
  transformations: Map<string, TypeTransformation>,
  schema: GraphQLSchema,
  debug: boolean
): Map<string, TypeTransformation> {
  const result = new Map<string, TypeTransformation>();
  const concreteOverrides = new Set<string>();

  for (const [key, transform] of transformations) {
    const type = schema.getType(transform.typeName);
    if (type && isObjectType(type)) {
      result.set(key, transform);
      concreteOverrides.add(`${transform.typeName}.${transform.fieldName}`);
    }
  }

  for (const transform of transformations.values()) {
    const type = schema.getType(transform.typeName);
    if (!type || !isInterfaceType(type)) {
      if (!type || !isObjectType(type)) {
        // Non-object, non-interface (union/scalar/enum/missing) — let the
        // downstream filter handle it. We still need to keep it in the map
        // so the filter can warn appropriately.
        const passthroughKey = `${transform.typeName}.${transform.fieldName}`;
        if (!result.has(passthroughKey)) {
          result.set(passthroughKey, transform);
        }
      }
      continue;
    }

    const implementingTypes = schema.getImplementations(type).objects;
    const fanOut: string[] = [];
    for (const concrete of implementingTypes) {
      const fields = concrete.getFields();
      if (!fields[transform.fieldName]) continue;

      const concreteKey = `${concrete.name}.${transform.fieldName}`;
      if (concreteOverrides.has(concreteKey)) continue;
      if (result.has(concreteKey)) continue;

      result.set(concreteKey, { ...transform, typeName: concrete.name });
      fanOut.push(concrete.name);
    }

    if (debug) {
      if (fanOut.length > 0) {
        console.warn(
          `[debug] Expanded ${transform.typeName}.${transform.fieldName} to: ${fanOut.join(', ')}`
        );
      } else {
        console.warn(
          `[debug] Interface "${transform.typeName}" has no implementing types with field "${transform.fieldName}"`
        );
      }
    }
  }

  return result;
}

/**
 * Group transformations by their type name
 */
function groupTransformationsByType(
  transformations: Map<string, TypeTransformation>
): Map<string, TypeTransformation[]> {
  const groups = new Map<string, TypeTransformation[]>();

  for (const transform of transformations.values()) {
    const existing = groups.get(transform.typeName) || [];
    existing.push(transform);
    groups.set(transform.typeName, existing);
  }

  return groups;
}

/**
 * Generate a transformed type for a single GraphQL type
 */
function generateTransformedType(
  graphqlType: GraphQLObjectType,
  transformations: TypeTransformation[],
  options: GeneratorOptions
): string {
  const lines: string[] = [];
  const typeName = graphqlType.name;
  const fields = graphqlType.getFields();

  lines.push('/**');
  lines.push(` * ${typeName} with type policy transformations applied.`);
  lines.push(' * Use this type when accessing data from Apollo Client cache.');
  lines.push(' */');
  lines.push(`export type ${typeName}WithTypePolicies = {`);
  lines.push(`  __typename?: '${typeName}';`);

  for (const [fieldName, field] of Object.entries(fields)) {
    const transformation = transformations.find((t) => t.fieldName === fieldName);

    if (transformation) {
      // Use transformed type
      let transformedType = transformation.transformedType;

      // Handle nullability preservation
      if (options.preserveNullability && !isNonNullType(field.type)) {
        // If the schema field is nullable and the transformed type doesn't already include null
        if (
          !transformation.isNullable &&
          !transformedType.includes('null') &&
          !transformedType.includes('undefined')
        ) {
          transformedType = `${transformedType} | null`;
        }
      }

      lines.push(`  ${fieldName}: ${transformedType};`);
    } else {
      // Keep original type - reference the base type
      lines.push(`  ${fieldName}: ${typeName}['${fieldName}'];`);
    }
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate utility types for working with transformed types
 */
function generateUtilityTypes(typeGroups: Map<string, TypeTransformation[]>): string {
  const lines: string[] = [];
  const typeNames = Array.from(typeGroups.keys());

  if (typeNames.length === 0) {
    return '';
  }

  lines.push('/**');
  lines.push(' * Apply type policy transformations to a type or query result.');
  lines.push(' *');
  lines.push(' * Recurses into nested objects and arrays, preserving the original');
  lines.push(' * selection — only fields with a registered type policy `read` are');
  lines.push(' * swapped to the post-transform type. Wrap any value that comes out');
  lines.push(' * of the Apollo cache (useQuery data, readFragment results, etc.).');
  lines.push(' *');
  lines.push(' * Usage: type Result = WithTypePolicies<GetUserQuery>');
  lines.push(' */');
  lines.push('export type WithTypePolicies<T> =');
  lines.push('  T extends null | undefined ? T :');
  lines.push(
    '  T extends ReadonlyArray<infer U> ? (T extends Array<infer U> ? Array<WithTypePolicies<U>> : ReadonlyArray<WithTypePolicies<U>>) :'
  );

  for (const [typeName, transforms] of typeGroups) {
    const fieldNames = transforms.map((t) => `'${t.fieldName}'`).join(' | ');
    lines.push(
      `  T extends { __typename?: '${typeName}' } ? { [K in keyof T]: K extends ${fieldNames} ? ${typeName}WithTypePolicies[K] : WithTypePolicies<T[K]> } :`
    );
  }

  lines.push('  T extends Date ? T :');
  lines.push('  T extends object ? { [K in keyof T]: WithTypePolicies<T[K]> } :');
  lines.push('  T;');
  lines.push('');

  // Generate a type that lists all types with transformations
  lines.push('/**');
  lines.push(' * Union of all type names that have type policy transformations.');
  lines.push(' */');
  lines.push(`export type TypesWithPolicies = ${typeNames.map((t) => `'${t}'`).join(' | ')};`);
  lines.push('');

  return lines.join('\n');
}
