import { GraphQLSchema, GraphQLObjectType, isObjectType, isNonNullType } from 'graphql';
import { TypeTransformation } from '../parser';
import { ResolvedTypePoliciesPluginConfig } from '../config';

/**
 * Options for type generation
 */
interface GeneratorOptions {
  preserveNullability: boolean;
  debug: boolean;
}

/**
 * Generate TypeScript type overrides based on extracted transformations
 */
export function generateTypeOverrides(
  schema: GraphQLSchema,
  transformations: Map<string, TypeTransformation>,
  config: ResolvedTypePoliciesPluginConfig
): string {
  const lines: string[] = [];
  const options: GeneratorOptions = {
    preserveNullability: config.preserveNullability,
    debug: config.debug,
  };

  // Header
  lines.push('/* eslint-disable */');
  lines.push('/* This file was generated by graphql-codegen-apollo-typepolicies */');
  lines.push('/* Do not edit this file directly */');
  lines.push('');

  if (transformations.size === 0) {
    lines.push('// No type policy transformations found');
    return lines.join('\n');
  }

  // Generate TypePolicyTransformations interface
  lines.push('/**');
  lines.push(' * Map of all type policy field transformations.');
  lines.push(' * Key format: "TypeName.fieldName"');
  lines.push(' */');
  lines.push('export interface TypePolicyTransformations {');

  for (const [key, transform] of transformations) {
    lines.push(`  '${key}': ${transform.transformedType};`);
  }

  lines.push('}');
  lines.push('');

  // Group transformations by type name
  const typeGroups = groupTransformationsByType(transformations);

  // Generate transformed type for each GraphQL type that has transformations
  for (const [typeName, fieldTransforms] of typeGroups) {
    const graphqlType = schema.getType(typeName);

    if (!graphqlType) {
      if (config.debug) {
        console.warn(`[debug] Type "${typeName}" not found in GraphQL schema, skipping`);
      }
      continue;
    }

    if (!isObjectType(graphqlType)) {
      if (config.debug) {
        console.warn(`[debug] Type "${typeName}" is not an object type, skipping`);
      }
      continue;
    }

    lines.push(generateTransformedType(graphqlType, fieldTransforms, options));
  }

  // Generate utility type for applying transformations to query results
  lines.push(generateUtilityTypes(typeGroups));

  return lines.join('\n');
}

/**
 * Group transformations by their type name
 */
function groupTransformationsByType(
  transformations: Map<string, TypeTransformation>
): Map<string, TypeTransformation[]> {
  const groups = new Map<string, TypeTransformation[]>();

  for (const transform of transformations.values()) {
    const existing = groups.get(transform.typeName) || [];
    existing.push(transform);
    groups.set(transform.typeName, existing);
  }

  return groups;
}

/**
 * Generate a transformed type for a single GraphQL type
 */
function generateTransformedType(
  graphqlType: GraphQLObjectType,
  transformations: TypeTransformation[],
  options: GeneratorOptions
): string {
  const lines: string[] = [];
  const typeName = graphqlType.name;
  const fields = graphqlType.getFields();

  lines.push('/**');
  lines.push(` * ${typeName} with type policy transformations applied.`);
  lines.push(' * Use this type when accessing data from Apollo Client cache.');
  lines.push(' */');
  lines.push(`export type ${typeName}WithTypePolicies = {`);
  lines.push(`  __typename?: '${typeName}';`);

  for (const [fieldName, field] of Object.entries(fields)) {
    const transformation = transformations.find(t => t.fieldName === fieldName);

    if (transformation) {
      // Use transformed type
      let transformedType = transformation.transformedType;

      // Handle nullability preservation
      if (options.preserveNullability && !isNonNullType(field.type)) {
        // If the schema field is nullable and the transformed type doesn't already include null
        if (!transformation.isNullable && !transformedType.includes('null') && !transformedType.includes('undefined')) {
          transformedType = `${transformedType} | null`;
        }
      }

      lines.push(`  ${fieldName}: ${transformedType};`);
    } else {
      // Keep original type - reference the base type
      lines.push(`  ${fieldName}: ${typeName}['${fieldName}'];`);
    }
  }

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate utility types for working with transformed types
 */
function generateUtilityTypes(typeGroups: Map<string, TypeTransformation[]>): string {
  const lines: string[] = [];
  const typeNames = Array.from(typeGroups.keys());

  if (typeNames.length === 0) {
    return '';
  }

  lines.push('/**');
  lines.push(' * Utility type to apply type policy transformations to a type.');
  lines.push(' * Maps a base type to its WithTypePolicies variant if available.');
  lines.push(' */');
  lines.push('export type WithTypePolicies<T> = ');

  // Generate conditional type mapping
  for (let i = 0; i < typeNames.length; i++) {
    const typeName = typeNames[i];
    const indent = i === 0 ? '  ' : '  : ';
    lines.push(`${indent}T extends { __typename?: '${typeName}' } ? ${typeName}WithTypePolicies`);
  }

  lines.push('  : T;');
  lines.push('');

  // Generate DeepWithTypePolicies - recursive version for operation types
  lines.push('/**');
  lines.push(' * Deep recursive utility type that applies type policy transformations');
  lines.push(' * throughout a nested query result type. Unlike WithTypePolicies, this');
  lines.push(' * preserves the original query selection (no field widening) and recurses');
  lines.push(' * into nested objects and arrays.');
  lines.push(' *');
  lines.push(' * Usage: type Result = DeepWithTypePolicies<GetUserQuery>');
  lines.push(' */');
  lines.push('export type DeepWithTypePolicies<T> =');
  lines.push('  T extends null | undefined ? T :');
  lines.push('  T extends ReadonlyArray<infer U> ? (T extends Array<infer U> ? Array<DeepWithTypePolicies<U>> : ReadonlyArray<DeepWithTypePolicies<U>>) :');

  for (const [typeName, transforms] of typeGroups) {
    const fieldNames = transforms.map(t => `'${t.fieldName}'`).join(' | ');
    lines.push(`  T extends { __typename?: '${typeName}' } ? { [K in keyof T]: K extends ${fieldNames} ? ${typeName}WithTypePolicies[K] : DeepWithTypePolicies<T[K]> } :`);
  }

  lines.push('  T extends Date ? T :');
  lines.push('  T extends object ? { [K in keyof T]: DeepWithTypePolicies<T[K]> } :');
  lines.push('  T;');
  lines.push('');

  // Generate a type that lists all types with transformations
  lines.push('/**');
  lines.push(' * Union of all type names that have type policy transformations.');
  lines.push(' */');
  lines.push(`export type TypesWithPolicies = ${typeNames.map(t => `'${t}'`).join(' | ')};`);
  lines.push('');

  return lines.join('\n');
}
